config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get "gallery" => "pages#gallery", as: :gallery
  get "admin" => "pages#admin", as: :admin
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @active_page = "home"
  end

  def gallery
    @active_page = "gallery"
  end

  def admin
    @active_page = "admin"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rise+Organize</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
  <body>
    </div class="page-header">
      <h1 class="header">RISE & ORGANIZE</h1>
    </div>

    <%= render 'partials/navbar' %> 

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<div>
    <div class="row">
      <div class="home-window col-xs-12 col-md-12 col-lg-12">
        
      </div>
    </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collaped" data-toggle="collapse" data-target="#main-navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navigation">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if @active_page == "home" %>"><%= link_to "HOME", root_path %></li>
        <li class="<%= "active" if @active_page == "gallery" %>"><%= link_to "GALLERY", gallery_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              Contact <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= mail_to "Helen@RiseAndOrganize.com" do %>
                  <strong>Email me:</strong> <span>helen@riseandorganize.com</span>
                <% end %>
              </li>
              <li>
                <a href="tel:+1-678-557-7842"><strong>Call me:</strong> +1 678 557-7842</a>
              </li>
            </ul>
          </li>
      </ul>

    </div>
  </div>
</nav>